# Generated by Django 3.0.2 on 2020-01-13 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='complted',
            new_name='completed',
        ),
    ]
